<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'title' => 'Introducción a Python para Principiantes',
                'description' => 'Aprende Python desde cero: variables, estructuras de control, funciones, manejo de archivos y proyectos reales. Ideal para quien nunca ha programado.',
                'instructor' => 'Ing. Carlos Mendoza',
                'rating' => 4.8,
                'students' => 12450,
                'price' => null,
                'category' => 'Programación',
                'duration' => '24 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Desarrollo Web con React y TypeScript',
                'description' => 'Domina React 18 con TypeScript, hooks, context API, React Query y despliegue en Vercel. Construye SPAs modernas con buenas prácticas.',
                'instructor' => 'Dra. Ana Gutiérrez',
                'rating' => 4.9,
                'students' => 8920,
                'price' => 499.00,
                'category' => 'Desarrollo Web',
                'duration' => '40 horas',
                'level' => 'Intermedio',
                'is_active' => true,
            ],
            [
                'title' => 'Machine Learning con Scikit-Learn',
                'description' => 'Implementa algoritmos de regresión, clasificación, clustering y validación de modelos. Incluye proyectos con datasets reales del INEGI.',
                'instructor' => 'Dr. Roberto Sánchez',
                'rating' => 4.7,
                'students' => 5340,
                'price' => 699.00,
                'category' => 'Ciencias de Datos',
                'duration' => '36 horas',
                'level' => 'Intermedio',
                'is_active' => true,
            ],
            [
                'title' => 'Diseño UX/UI con Figma',
                'description' => 'Crea interfaces atractivas y funcionales. Aprende investigación de usuario, wireframes, prototipos interactivos y sistemas de diseño.',
                'instructor' => 'Lic. Valeria Torres',
                'rating' => 4.6,
                'students' => 7210,
                'price' => 399.00,
                'category' => 'Diseño',
                'duration' => '28 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Emprendimiento Digital para Jóvenes',
                'description' => 'Valida tu idea de negocio, construye un MVP, atrae primeros clientes y escala usando herramientas digitales accesibles desde México.',
                'instructor' => 'MBA. Fernanda Ríos',
                'rating' => 4.5,
                'students' => 9870,
                'price' => null,
                'category' => 'Negocios',
                'duration' => '20 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Inglés Profesional para Tecnología',
                'description' => 'Vocabulario técnico en inglés para leer documentación, escribir código comentado, participar en reuniones y conseguir trabajo en empresas globales.',
                'instructor' => 'Mtra. Sandra Leal',
                'rating' => 4.7,
                'students' => 11200,
                'price' => 349.00,
                'category' => 'Idiomas',
                'duration' => '32 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Liderazgo y Trabajo en Equipo',
                'description' => 'Desarrolla habilidades de comunicación asertiva, gestión de conflictos, delegación efectiva y liderazgo situacional en entornos profesionales.',
                'instructor' => 'Dr. Alejandro Morales',
                'rating' => 4.4,
                'students' => 6540,
                'price' => 299.00,
                'category' => 'Habilidades Blandas',
                'duration' => '16 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Cálculo Diferencial e Integral',
                'description' => 'Fundamentos sólidos de límites, derivadas, integrales y sus aplicaciones en ingeniería. Incluye resolución de problemas tipo EXANI-III.',
                'instructor' => 'Dr. Miguel Ángel Vega',
                'rating' => 4.6,
                'students' => 4320,
                'price' => 449.00,
                'category' => 'Matemáticas',
                'duration' => '48 horas',
                'level' => 'Intermedio',
                'is_active' => true,
            ],
            [
                'title' => 'Laravel 12: APIs RESTful con PHP',
                'description' => 'Construye APIs robustas con Laravel 12, autenticación Sanctum, testing con PHPUnit, documentación Swagger y deploy en Railway.',
                'instructor' => 'Ing. Jorge Pacheco',
                'rating' => 4.8,
                'students' => 3890,
                'price' => 599.00,
                'category' => 'Desarrollo Web',
                'duration' => '44 horas',
                'level' => 'Avanzado',
                'is_active' => true,
            ],
            [
                'title' => 'Análisis de Datos con Excel y Power BI',
                'description' => 'Transforma datos crudos en dashboards ejecutivos. Aprende tablas dinámicas, DAX, modelado y visualización para toma de decisiones.',
                'instructor' => 'Lic. Patricia Montoya',
                'rating' => 4.5,
                'students' => 15600,
                'price' => 249.00,
                'category' => 'Ciencias de Datos',
                'duration' => '22 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Algoritmos y Estructuras de Datos en Java',
                'description' => 'Listas enlazadas, árboles, grafos, ordenamiento y búsqueda. Preparación para entrevistas técnicas en empresas FAANG y startups.',
                'instructor' => 'Dr. Luis Herrera',
                'rating' => 4.9,
                'students' => 2760,
                'price' => 799.00,
                'category' => 'Programación',
                'duration' => '52 horas',
                'level' => 'Avanzado',
                'is_active' => true,
            ],
            [
                'title' => 'SQL y Bases de Datos Relacionales',
                'description' => 'Diseño de esquemas, consultas complejas, joins, subconsultas, índices y optimización. Compatible con MySQL, PostgreSQL y SQLite.',
                'instructor' => 'Ing. Diana Castillo',
                'rating' => 4.7,
                'students' => 10800,
                'price' => null,
                'category' => 'Programación',
                'duration' => '26 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Finanzas Personales para Universitarios',
                'description' => 'Presupuesto mensual, ahorro de emergencia, AFORE, inversión en CETES y deuda estudiantil. Conceptos adaptados al contexto mexicano.',
                'instructor' => 'Lic. Gustavo Reyes',
                'rating' => 4.6,
                'students' => 18400,
                'price' => null,
                'category' => 'Negocios',
                'duration' => '12 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Diseño Gráfico con Adobe Illustrator',
                'description' => 'Vectores, tipografía, color, composición y branding. Crea logotipos, flyers e identidad visual profesional desde cero.',
                'instructor' => 'Lic. Mónica Serrano',
                'rating' => 4.4,
                'students' => 5930,
                'price' => 379.00,
                'category' => 'Diseño',
                'duration' => '30 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Inteligencia Artificial: Fundamentos y ChatGPT API',
                'description' => 'Entiende cómo funcionan los LLMs, integra la API de OpenAI en tus proyectos y construye aplicaciones con IA generativa paso a paso.',
                'instructor' => 'Dr. Héctor Domínguez',
                'rating' => 4.8,
                'students' => 7650,
                'price' => 649.00,
                'category' => 'Ciencias de Datos',
                'duration' => '34 horas',
                'level' => 'Intermedio',
                'is_active' => true,
            ],
            [
                'title' => 'Desarrollo de Apps Móviles con Flutter',
                'description' => 'Crea apps nativas para iOS y Android con un solo código base. Estado con Bloc, navegación, consumo de APIs y publicación en tiendas.',
                'instructor' => 'Ing. Ramón Fuentes',
                'rating' => 4.6,
                'students' => 4100,
                'price' => 549.00,
                'category' => 'Programación',
                'duration' => '46 horas',
                'level' => 'Intermedio',
                'is_active' => true,
            ],
            [
                'title' => 'Estadística Aplicada para Negocios',
                'description' => 'Probabilidad, distribuciones, pruebas de hipótesis y regresión lineal con aplicaciones reales en marketing, producción y recursos humanos.',
                'instructor' => 'Dra. Claudia Espinoza',
                'rating' => 4.5,
                'students' => 3450,
                'price' => 399.00,
                'category' => 'Matemáticas',
                'duration' => '30 horas',
                'level' => 'Intermedio',
                'is_active' => true,
            ],
            [
                'title' => 'Git y GitHub: Control de Versiones Profesional',
                'description' => 'Domina ramas, merges, rebase, pull requests, GitHub Actions y flujo de trabajo en equipos. Esencial para cualquier desarrollador.',
                'instructor' => 'Ing. Adrián Luna',
                'rating' => 4.8,
                'students' => 22100,
                'price' => null,
                'category' => 'Programación',
                'duration' => '10 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Marketing Digital y Redes Sociales',
                'description' => 'Estrategia de contenidos, SEO básico, publicidad en Meta e Instagram, email marketing y análisis de métricas para PyMEs mexicanas.',
                'instructor' => 'Lic. Paola Jiménez',
                'rating' => 4.3,
                'students' => 13800,
                'price' => 279.00,
                'category' => 'Negocios',
                'duration' => '18 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'Comunicación Efectiva y Oratoria',
                'description' => 'Habla en público con confianza, elabora presentaciones impactantes y desarrolla escucha activa. Incluye simulacros de entrevistas laborales.',
                'instructor' => 'Mtra. Elena Vargas',
                'rating' => 4.5,
                'students' => 8760,
                'price' => null,
                'category' => 'Habilidades Blandas',
                'duration' => '14 horas',
                'level' => 'Principiante',
                'is_active' => true,
            ],
            [
                'title' => 'DevOps: Docker, CI/CD y Kubernetes',
                'description' => 'Containeriza aplicaciones, automatiza pipelines con GitHub Actions y gestiona clusters con Kubernetes. Para equipos de desarrollo modernos.',
                'instructor' => 'Ing. Francisco Peña',
                'rating' => 4.7,
                'students' => 2340,
                'price' => 899.00,
                'category' => 'Programación',
                'duration' => '56 horas',
                'level' => 'Avanzado',
                'is_active' => true,
            ],
            [
                'title' => 'Álgebra Lineal para Machine Learning',
                'description' => 'Vectores, matrices, transformaciones lineales, valores propios y descomposición SVD. La matemática detrás de las redes neuronales, explicada visualmente.',
                'instructor' => 'Dr. Ernesto Alamilla',
                'rating' => 4.8,
                'students' => 1980,
                'price' => 499.00,
                'category' => 'Matemáticas',
                'duration' => '40 horas',
                'level' => 'Avanzado',
                'is_active' => true,
            ],
        ];

        foreach ($courses as $course) {
            Course::updateOrCreate(
                ['title' => $course['title']],
                $course
            );
        }

        $this->command->info(count($courses) . ' cursos creados correctamente');
    }
}
