<?php

namespace Database\Seeders;

use App\Models\Scholarship;
use Illuminate\Database\Seeder;

class ScholarshipSeeder extends Seeder
{
    public function run(): void
    {
        $scholarships = [
            [
                'name' => 'Beca Benito Juárez para Educación Superior',
                'description' => 'Programa federal que apoya económicamente a estudiantes de familias en situación de pobreza o vulnerabilidad inscritos en instituciones públicas de educación superior. Cubre manutención mensual durante el periodo escolar.',
                'provider' => 'Secretaría de Educación Pública (SEP)',
                'amount' => 2400.00,
                'currency' => 'MXN',
                'coverage' => 'monthly',
                'level' => 'Licenciatura',
                'career' => null,
                'application_start' => '2026-07-01',
                'application_end' => '2026-08-31',
                'results_date' => '2026-09-30',
                'requirements' => 'Estar inscrito en institución pública, promedio mínimo 7.0, carta socioeconómica, CURP, credencial de elector o acta de nacimiento',
                'document_url' => null,
                'contact_email' => 'becasuperior@sep.gob.mx',
                'contact_phone' => '800 288 6688',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Beca CONACYT — Posgrado Nacional',
                'description' => 'Financiamiento integral para cursar maestría o doctorado en programas de calidad reconocidos por el PNPC. Incluye manutención mensual, seguro de gastos médicos y apoyo para traslados. La beca más competida del país para posgrado.',
                'provider' => 'Consejo Nacional de Ciencia y Tecnología (CONACYT)',
                'amount' => 14000.00,
                'currency' => 'MXN',
                'coverage' => 'monthly',
                'level' => 'Posgrado',
                'career' => null,
                'application_start' => '2026-01-15',
                'application_end' => '2026-03-31',
                'results_date' => '2026-05-15',
                'requirements' => 'Carta de aceptación en programa PNPC, título de licenciatura, promedio mínimo 8.0, carta de exposición de motivos, CV actualizado, dos cartas de recomendación académica',
                'document_url' => null,
                'contact_email' => 'becasnacionales@conacyt.mx',
                'contact_phone' => '55 5322 7700',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Beca de Excelencia Académica ANUIES',
                'description' => 'Reconocimiento y apoyo económico para los mejores promedios de instituciones afiliadas a la ANUIES. Además del estímulo monetario, incluye acceso a redes de investigación y movilidad estudiantil nacional.',
                'provider' => 'Asociación Nacional de Universidades (ANUIES)',
                'amount' => 8500.00,
                'currency' => 'MXN',
                'coverage' => 'parcial',
                'level' => 'Licenciatura',
                'career' => null,
                'application_start' => '2026-08-01',
                'application_end' => '2026-09-15',
                'results_date' => '2026-10-01',
                'requirements' => 'Promedio mínimo 9.5, carta de la institución, ensayo académico de 500 palabras, carta de no adeudo',
                'document_url' => null,
                'contact_email' => 'excelencia@anuies.mx',
                'contact_phone' => '55 5420 4900',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Beca Jóvenes Escribiendo el Futuro',
                'description' => 'Apoyo para jóvenes de familias en desventaja económica, provenientes de municipios con alto índice de rezago social o de grupos indígenas y afromexicanos. Complementaria a la Beca Benito Juárez para gastos adicionales.',
                'provider' => 'Secretaría de Educación Pública (SEP)',
                'amount' => 900.00,
                'currency' => 'MXN',
                'coverage' => 'monthly',
                'level' => 'Licenciatura',
                'career' => null,
                'application_start' => '2026-07-15',
                'application_end' => '2026-08-30',
                'results_date' => '2026-09-20',
                'requirements' => 'Vivir en municipio de alta marginación o pertenecer a comunidad indígena, inscripción vigente en institución pública, estudio socioeconómico',
                'document_url' => null,
                'contact_email' => 'jovenes_futuro@sep.gob.mx',
                'contact_phone' => '800 288 6688',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Beca Tamaulipas — Talento Universitario',
                'description' => 'Programa estatal para estudiantes de universidades tecnológicas y politécnicas de Tamaulipas con alto rendimiento académico. Cubre parte de inscripción y materiales escolares durante el semestre.',
                'provider' => 'Gobierno del Estado de Tamaulipas',
                'amount' => 3500.00,
                'currency' => 'MXN',
                'coverage' => 'parcial',
                'level' => 'Licenciatura',
                'career' => null,
                'application_start' => '2026-06-01',
                'application_end' => '2026-07-31',
                'results_date' => '2026-08-20',
                'requirements' => 'Promedio mínimo 8.5, residencia en Tamaulipas, carta de la institución, comprobante de domicilio',
                'document_url' => null,
                'contact_email' => 'becas@tamaulipas.gob.mx',
                'contact_phone' => '834 318 1800',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Beca PRONABES — Programa Nacional de Becas',
                'description' => 'Apoyo económico de largo plazo para estudiantes de escasos recursos inscritos en IES públicas. Renovable cada semestre con requisito de avance académico satisfactorio.',
                'provider' => 'Secretaría de Educación Pública (SEP)',
                'amount' => 750.00,
                'currency' => 'MXN',
                'coverage' => 'monthly',
                'level' => 'Licenciatura',
                'career' => null,
                'application_start' => '2026-08-15',
                'application_end' => '2026-10-01',
                'results_date' => '2026-11-01',
                'requirements' => 'Inscripción en IES pública, estudio socioeconómico, promedio aprobatorio, no contar con otra beca gubernamental de manutención',
                'document_url' => null,
                'contact_email' => 'pronabes@sep.gob.mx',
                'contact_phone' => '800 288 6688',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Beca Microsoft — Programa Mujeres en Tech',
                'description' => 'Apoyo exclusivo para mujeres estudiantes de carreras de tecnología en México. Incluye el beneficio económico más acceso a mentoría con ingenieras de Microsoft, certificaciones Azure y acceso a eventos de la industria.',
                'provider' => 'Microsoft México',
                'amount' => 15000.00,
                'currency' => 'MXN',
                'coverage' => 'parcial',
                'level' => 'Licenciatura',
                'career' => 'Ingeniería en Sistemas, Ingeniería en Software, Ciencias de la Computación, TI',
                'application_start' => '2026-03-01',
                'application_end' => '2026-04-30',
                'results_date' => '2026-05-31',
                'requirements' => 'Mujer cursando carrera de tecnología, promedio mínimo 8.0, carta de motivación, video de 2 minutos explicando por qué quieres trabajar en tecnología',
                'document_url' => null,
                'contact_email' => 'mujeresentech@microsoft.com',
                'contact_phone' => null,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Beca Google — Generación G',
                'description' => 'Programa de Google para apoyar a jóvenes de comunidades subrepresentadas en tecnología. Incluye financiamiento parcial, acceso a cursos de Google Career Certificates y posibilidad de pasantía.',
                'provider' => 'Google México',
                'amount' => 20000.00,
                'currency' => 'MXN',
                'coverage' => 'parcial',
                'level' => 'Licenciatura',
                'career' => 'Ingeniería, Ciencias de la Computación, Matemáticas',
                'application_start' => '2026-04-01',
                'application_end' => '2026-05-31',
                'results_date' => '2026-07-01',
                'requirements' => 'Estudiante de primer generación universitaria, carrera STEM, promedio mínimo 8.0, ensayo sobre impacto comunitario, carta de la institución',
                'document_url' => null,
                'contact_email' => 'generaciong@google.com',
                'contact_phone' => null,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Beca OEA — Programa de Becas para el Desarrollo',
                'description' => 'La Organización de Estados Americanos ofrece financiamiento completo para posgrados en cualquier país miembro. Incluye manutención, pasajes aéreos, seguro médico y matrícula. Proceso altamente competitivo.',
                'provider' => 'Organización de Estados Americanos (OEA)',
                'amount' => 0.00,
                'currency' => 'USD',
                'coverage' => 'total',
                'level' => 'Posgrado',
                'career' => null,
                'application_start' => '2026-09-01',
                'application_end' => '2026-11-30',
                'results_date' => '2027-02-28',
                'requirements' => 'Título de licenciatura con promedio mínimo 8.5, dominio del idioma del país destino, propuesta de investigación, dos cartas de recomendación, carta de aceptación provisional de institución en el extranjero',
                'document_url' => null,
                'contact_email' => 'scholar@oas.org',
                'contact_phone' => '+1 202 458 3000',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Beca Fulbright García-Robles — EUA',
                'description' => 'Programa binacional México-EUA para realizar maestría o doctorado en universidades de los Estados Unidos. Financia matrícula completa, manutención mensual, pasajes y seguro de salud por hasta 2 años.',
                'provider' => 'Comisión México-Estados Unidos para el Intercambio Educativo (COMEXUS)',
                'amount' => 0.00,
                'currency' => 'USD',
                'coverage' => 'total',
                'level' => 'Posgrado',
                'career' => null,
                'application_start' => '2026-01-10',
                'application_end' => '2026-06-30',
                'results_date' => '2026-10-15',
                'requirements' => 'Ciudadanía mexicana, título de licenciatura, TOEFL mínimo 80 iBT, GRE o GMAT según área, carta de motivación, propuesta académica, tres cartas de recomendación, promedio mínimo 8.5',
                'document_url' => null,
                'contact_email' => 'comexus@comexus.org.mx',
                'contact_phone' => '55 5208 5016',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Beca ITESM — Excelencia Académica',
                'description' => 'El Tecnológico de Monterrey ofrece becas de hasta el 100% de matrícula para estudiantes con promedio sobresaliente de bachillerato. Incluye acceso a mentoría, actividades extracurriculares y red de egresados.',
                'provider' => 'Instituto Tecnológico y de Estudios Superiores de Monterrey (ITESM)',
                'amount' => 0.00,
                'currency' => 'MXN',
                'coverage' => 'total',
                'level' => 'Licenciatura',
                'career' => null,
                'application_start' => '2026-10-01',
                'application_end' => '2026-11-30',
                'results_date' => '2026-12-20',
                'requirements' => 'Promedio bachillerato mínimo 95/100, Examen de Admisión Tec, carta de recomendación de director de escuela, comprobante de ingresos familiares',
                'document_url' => null,
                'contact_email' => 'becas@tec.mx',
                'contact_phone' => '800 832 6671',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Beca Santander — Investigación Universitaria',
                'description' => 'Financiamiento para proyectos de investigación de estudiantes de licenciatura y posgrado en colaboración con profesores. Apoya gastos de materiales, viajes a congresos y publicación de resultados.',
                'provider' => 'Santander Universidades México',
                'amount' => 25000.00,
                'currency' => 'MXN',
                'coverage' => 'parcial',
                'level' => 'Licenciatura',
                'career' => null,
                'application_start' => '2026-02-01',
                'application_end' => '2026-03-15',
                'results_date' => '2026-04-30',
                'requirements' => 'Inscripción en institución aliada Santander, propuesta de investigación con tutor académico, promedio mínimo 8.0, carta del tutor responsable',
                'document_url' => null,
                'contact_email' => 'becas@santander.com.mx',
                'contact_phone' => '55 5257 8000',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Beca Mujeres Rurales — SEDESOL Tamaulipas',
                'description' => 'Apoyo especial para mujeres provenientes de zonas rurales de Tamaulipas que deseen cursar estudios universitarios. Cubre transportación, materiales y una beca mensual de manutención.',
                'provider' => 'Secretaría de Desarrollo Social Tamaulipas',
                'amount' => 1800.00,
                'currency' => 'MXN',
                'coverage' => 'monthly',
                'level' => 'Licenciatura',
                'career' => null,
                'application_start' => '2026-07-01',
                'application_end' => '2026-08-15',
                'results_date' => '2026-09-01',
                'requirements' => 'Mujer, residencia en zona rural de Tamaulipas (menos de 15,000 habitantes), inscripción en institución pública, estudio socioeconómico, acta de nacimiento',
                'document_url' => null,
                'contact_email' => 'sedesol@tamaulipas.gob.mx',
                'contact_phone' => '834 318 1800',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Beca DAAD — Alemania para México',
                'description' => 'El Servicio Alemán de Intercambio Académico (DAAD) financia estancias de investigación, maestrías y doctorados en universidades alemanas de clase mundial. Incluye manutención, seguro de salud y cursos de alemán.',
                'provider' => 'DAAD (Servicio Alemán de Intercambio Académico)',
                'amount' => 0.00,
                'currency' => 'EUR',
                'coverage' => 'total',
                'level' => 'Posgrado',
                'career' => 'Ingeniería, Ciencias Exactas, Humanidades, Ciencias Sociales',
                'application_start' => '2026-06-01',
                'application_end' => '2026-10-31',
                'results_date' => '2027-01-31',
                'requirements' => 'Título de licenciatura o estar en último año, inglés o alemán B2+, propuesta de investigación o plan de estudios, CV, dos cartas de recomendación académica',
                'document_url' => null,
                'contact_email' => 'mexico@daad.de',
                'contact_phone' => '55 5207 3422',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Beca Nacional de Tecnología e Innovación — INADEM',
                'description' => 'Apoyo para estudiantes universitarios que desarrollen proyectos de innovación tecnológica aplicados a problemas reales de PyMEs mexicanas. Incluye financiamiento, mentoría de empresarios y posibilidad de incubación.',
                'provider' => 'Instituto Nacional del Emprendedor (INADEM)',
                'amount' => 12000.00,
                'currency' => 'MXN',
                'coverage' => 'parcial',
                'level' => 'Licenciatura',
                'career' => 'Ingeniería, Tecnología, Diseño, Administración',
                'application_start' => '2026-03-15',
                'application_end' => '2026-05-15',
                'results_date' => '2026-06-30',
                'requirements' => 'Proyecto de innovación con viabilidad demostrable, equipo de máximo 4 integrantes, carta de institución, plan de negocios básico, prototipo o evidencia de avance',
                'document_url' => null,
                'contact_email' => 'innovacion@inadem.gob.mx',
                'contact_phone' => '01 800 463 2336',
                'is_active' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($scholarships as $scholarship) {
            Scholarship::updateOrCreate(
                ['name' => $scholarship['name']],
                $scholarship
            );
        }

        $this->command->info(count($scholarships) . ' becas creadas correctamente');
    }
}
